FROM mysql:8.0.36-oracle

RUN unlink /etc/localtime \
    && ln -s /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime

# ref: https://stackoverflow.com/questions/71239450/gpg-keys-issue-while-installing-mysql-community-server
RUN rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023

RUN microdnf update -y
RUN microdnf install -y curl procps cronie rsync python3 python3-pip

# mysql8 - has no tar
RUN microdnf install -y tar

# RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
#     && python get-pip.py \
#     && pip install awscli
RUN pip3 install supervisor awscli

RUN microdnf install nodejs -y
RUN npm -g i nodemon
