FROM wordpress:php8.0-apache

RUN apt update -y
RUN apt install curl python3 python3-pip supervisor procps cron rsync -y

# RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
#     && python get-pip.py \
#     && pip install awscli
RUN pip3 install awscli

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash -
RUN apt install nodejs -y
RUN npm -g i nodemon

RUN docker-php-ext-install pdo_mysql