FROM wordpress:php5.6-apache

RUN unlink /etc/localtime \
    && ln -s /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime

# ref: https://unix.stackexchange.com/questions/743839/apt-get-update-failed-to-fetch-debian-amd64-packages-while-building-dockerfile-f
RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list

RUN apt update -y --no-install-recommends
RUN apt install curl python3 python3-pip supervisor procps cron rsync -y

# RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
#     && python get-pip.py \
#     && pip install awscli
RUN pip3 install awscli

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt install nodejs -y
RUN npm -g i nodemon

RUN docker-php-ext-install pdo_mysql

RUN apt -y install openssh-server && mkdir /run/sshd

COPY ssh/sshd_config /etc/ssh/sshd_config