name: Build image

on:
  push:
    branches:
      - master

    tags:
      - '*'

env:
  IMAGE_ID: lncknight/wordpress

jobs:

  wp:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      PREFIX: wp
      FOLDER: docker_wp

    ############ COMMON SCRIPT buildx ############
    steps:
      - uses: actions/checkout@v2

      # - name: Build image
      #   run: docker buildx build . --file ${FOLDER}/Dockerfile --tag $IMAGE_NAME

      # ref: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      # ref: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v1-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker buildx build --file ${FOLDER}/Dockerfile --platform linux/amd64,linux/arm64 $FOLDER --tag $IMAGE_ID:${PREFIX}-$(date +"%Y%m%d") --push

  nginx:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      PREFIX: nginx
      FOLDER: docker_nginx

    ############ COMMON SCRIPT buildx ############
    steps:
      - uses: actions/checkout@v2

      # - name: Build image
      #   run: docker buildx build . --file ${FOLDER}/Dockerfile --tag $IMAGE_NAME

      # ref: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      # ref: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-v1-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker buildx build --file ${FOLDER}/Dockerfile --platform linux/amd64,linux/arm64 $FOLDER --tag $IMAGE_ID:${PREFIX}-$(date +"%Y%m%d") --push

  mysql:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      matrix:
        version: [57, 80]
        platforms: ["linux/amd64", "linux/amd64,linux/arm64"]
        exclude:
          - version: 57
            platform: "linux/amd64,linux/arm64"
          - version: 80
            platform: "linux/amd64"

    env:
      PREFIX: mysql
      FOLDER: docker_mysql

    ############ COMMON SCRIPT buildx matrix ############
    steps:
      - uses: actions/checkout@v2

      # - name: Build image
      #   run: docker buildx build . --file ${FOLDER}/Dockerfile --tag $IMAGE_NAME

      # ref: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      # ref: https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.version }}-buildx-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.version }}-buildx-v1-
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker buildx build --file ${FOLDER}/Dockerfile.${{ matrix.version }} --platform ${{ matrix.platform }} $FOLDER --tag $IMAGE_ID:${PREFIX}-$(date +"%Y%m%d")-${{ matrix.version }} --push